export const AgentData = [
  {
    id: "1",
    district: "Ariyalur",
    agentName: "Christian",
    productName: "Black Sesame",
    quantity: "425 Kg",
    lots: "46",
    bags: "34",
    dateOfProcurement: "21-9-2023",
    quality: "Q-A1",
    biddingStatus: "Pre Bid",
    procurementId: "88",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "2",
    district: "Bodinayaknur",
    agentName: "Juan",
    productName: "Black Sesame",
    quantity: "480 Kg",
    lots: "15",
    bags: "31",
    dateOfProcurement: "21-8-2023",
    quality: "Q-A2",
    biddingStatus: "Post bid",
    procurementId: "100",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "3",
    district: "Cuddalore",
    agentName: "Emilie",
    productName: "Black Sesame",
    quantity: "402 Kg",
    lots: "32",
    bags: "99",
    dateOfProcurement: "10-8-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "81",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "4",
    district: "Velur",
    agentName: "Amy",
    productName: "White Sesame",
    quantity: "400 Kg",
    lots: "9",
    bags: "85",
    dateOfProcurement: "20-7-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "1",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "5",
    district: "Kanyakumari",
    agentName: "Derek",
    productName: "Black Sesame",
    quantity: "425 Kg",
    lots: "37",
    bags: "70",
    dateOfProcurement: "23-7-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "40",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "6",
    district: "Theni",
    agentName: "Isabelle",
    productName: "Red Sesame",
    quantity: "467 Kg",
    lots: "50",
    bags: "31",
    dateOfProcurement: "27-5-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "68",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "7",
    district: "Tirunelveli",
    agentName: "Gene",
    productName: "Black Sesame",
    quantity: "477 Kg",
    lots: "50",
    bags: "52",
    dateOfProcurement: "19-5-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "40",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "8",
    district: "Dindugal",
    agentName: "Carl",
    productName: "Red Sesame",
    quantity: "446 Kg",
    lots: "38",
    bags: "64",
    dateOfProcurement: "27-11-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "89",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "9",
    district: "Vilupuram",
    agentName: "Lawrence",
    productName: "Black Sesame",
    quantity: "441 Kg",
    lots: "42",
    bags: "96",
    dateOfProcurement: "24-12-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "988",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "29",
    district: "Erode",
    agentName: "Bertha",
    productName: "Black Sesame",
    quantity: "449 Kg",
    lots: "31",
    bags: "40",
    dateOfProcurement: "23-3-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "709",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "12",
    district: "Madurai",
    agentName: "Harold",
    productName: "White Sesame",
    quantity: "442 Kg",
    lots: "30",
    bags: "82",
    dateOfProcurement: "30-1-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "41",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "20",
    district: "Tiruppur",
    agentName: "Tom",
    productName: "Red Sesame",
    quantity: "404 Kg",
    lots: "24",
    bags: "70",
    dateOfProcurement: "13-11-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "54",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "51",
    district: "Kanchipuram",
    agentName: "Tillie",
    productName: "White Sesame",
    quantity: "452 Kg",
    lots: "1",
    bags: "96",
    dateOfProcurement: "15-4-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "68",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "27",
    district: "Chengalpattu",
    agentName: "Louisa",
    productName: "White Sesame",
    quantity: "460 Kg",
    lots: "1",
    bags: "54",
    dateOfProcurement: "6-1-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "69",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "34",
    district: "Karaikkal",
    agentName: "Bruce",
    productName: "Black Sesame",
    quantity: "402 Kg",
    lots: "33",
    bags: "71",
    dateOfProcurement: "1-11-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "7",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "74",
    district: "Nagapattinam",
    agentName: "Lena",
    productName: "Red Sesame",
    quantity: "456 Kg",
    lots: "13",
    bags: "59",
    dateOfProcurement: "20-1-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "25",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "85",
    district: "The Nilgiris",
    agentName: "Myrtle",
    productName: "Red Sesame",
    quantity: "445 Kg",
    lots: "4",
    bags: "35",
    dateOfProcurement: "24-12-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "45",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "97",
    district: "Sivagangai",
    agentName: "Jerome",
    productName: "White Sesame",
    quantity: "463 Kg",
    lots: "2",
    bags: "74",
    dateOfProcurement: "2-4-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "93",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "66",
    district: "Coimbatore",
    agentName: "Justin",
    productName: "Black Sesame",
    quantity: "440 Kg",
    lots: "47",
    bags: "83",
    dateOfProcurement: "21-3-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "59",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "38",
    district: "Viruthunagar",
    agentName: "Nell",
    productName: "White Sesame",
    quantity: "427 Kg",
    lots: "27",
    bags: "54",
    dateOfProcurement: "26-4-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "61",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "84",
    district: "Ramanathapuram",
    agentName: "Bruce",
    productName: "White Sesame",
    quantity: "424 Kg",
    lots: "34",
    bags: "42",
    dateOfProcurement: "28-8-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "74",
    procurementDistrictStatus: "other",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
  {
    id: "67",
    district: "Ranipet",
    agentName: "Don",
    productName: "Red Sesame",
    quantity: "410 Kg",
    lots: "40",
    bags: "77",
    dateOfProcurement: "13-10-2023",
    quality: "Q-B1",
    biddingStatus: "Declined",
    procurementId: "47",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
];
