export const CompetitorsData = [
  {
    id: "1",
    CompetitorsName: "Vignesh Oil Factory",
    district: "Ariyalur",
    agentName: "Christian",
    productName: "Black Sesame",
    quantity: "425",
    lots: "46",
    bags: "34",
    dateOfProcurement: "21-9-2023",
    quality: "Q-A1",
    biddingStatus: "Pre Bid",
    procurementId: "88",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwar,t",
    ],
  },
  {
    id: "2",
    CompetitorsName: "Kalithas Oil Factory",
    district: "Ariyalur",
    agentName: "Christian",
    productName: "Black Sesame",
    quantity: "425",
    lots: "46",
    bags: "34",
    dateOfProcurement: "21-9-2023",
    quality: "Q-A1",
    biddingStatus: "Pre Bid",
    procurementId: "88",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwar,t",
    ],
  },
  {
    id: "3",
    CompetitorsName: "Kalam Oil Factory",
    district: "Ariyalur",
    agentName: "Christian",
    productName: "Black Sesame",
    quantity: "425",
    lots: "46",
    bags: "34",
    dateOfProcurement: "21-9-2023",
    quality: "Q-A1",
    biddingStatus: "Pre Bid",
    procurementId: "88",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwar,t",
    ],
  },
  {
    id: "4",
    CompetitorsName: "Dilip Oil Factory",
    district: "Ariyalur",
    agentName: "Christian",
    productName: "Black Sesame",
    quantity: "425",
    lots: "46",
    bags: "34",
    dateOfProcurement: "21-9-2023",
    quality: "Q-A1",
    biddingStatus: "Pre Bid",
    procurementId: "88",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwar,t",
    ],
  },
  {
    id: "5",
    CompetitorsName: "Sarabesh Oil Factory",
    district: "Ariyalur",
    agentName: "Christian",
    productName: "Black Sesame",
    quantity: "425",
    lots: "46",
    bags: "34",
    dateOfProcurement: "21-9-2023",
    quality: "Q-A1",
    biddingStatus: "Pre Bid",
    procurementId: "88",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwar,t",
    ],
  },
  {
    id: "6",
    CompetitorsName: "Manoj Oil Factory",
    district: "Ariyalur",
    agentName: "Christian",
    productName: "Black Sesame",
    quantity: "425",
    lots: "46",
    bags: "34",
    dateOfProcurement: "21-9-2023",
    quality: "Q-A1",
    biddingStatus: "Pre Bid",
    procurementId: "88",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwar,t",
    ],
  },
  {
    id: "7",
    CompetitorsName: "Revanth Oil Factory",
    district: "Ariyalur",
    agentName: "Christian",
    productName: "Black Sesame",
    quantity: "425",
    lots: "46",
    bags: "34",
    dateOfProcurement: "21-9-2023",
    quality: "Q-A1",
    biddingStatus: "Pre Bid",
    procurementId: "88",
    procurementDistrictStatus: "own",
    agents: [
      "Ruben Curtis Sam",
      "Marliyn Gouse",
      "Gretchen Kenter",
      "Emerson Dorwart",
    ],
  },
];
