import { StyleSheet, Platform, StatusBar, Dimensions } from "react-native";
import {
  COLORS,
  WEIGHT,
  SIZES,
  FONT,
  ASPECTRADIO,
  UNIQUEWIDTH,
} from "../Constants";
import {
  fontPixel,
  heightPixel,
  pixelSizeHorizontal,
  pixelSizeVertical,
  widthPixel,
} from "./Responsive";

export default StyleSheet.create({
  statisticContainer: {
    width: UNIQUEWIDTH.wid,
    height: heightPixel(330),
    backgroundColor: COLORS.Secondary,
    borderRadius: 6,
    marginVertical: pixelSizeVertical(10),
  },
  inputBox: {
    width: widthPixel(375),
    height: heightPixel(48),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#D5E8FF",
    paddingHorizontal: 15,
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.size14,
    color: COLORS.PrimaryText,
  },
  LoginButton: {
    width: widthPixel(375),
    height: heightPixel(48),
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  LoginBtnText: {
    fontFamily: FONT.EuclidSemiBold,
    fontStyle: "normal",
    fontSize: SIZES.size14,
    color: COLORS.white,
  },

  HeadLine: {
    fontFamily: FONT.EuclidSemiBold,
    fontStyle: "normal",
    fontSize: SIZES.large,
    color: COLORS.PrimaryText,
  },
  Label: {
    fontFamily: FONT.EuclidMedium,
    // fontStyle: "normal",
    fontSize: SIZES.small,
    color: COLORS.PrimaryText,
  },
  ErrorInputBorder: {
    borderWidth: 1,
    borderColor: COLORS.ErrorRed,
  },
  ErrorText: {
    fontFamily: FONT.EuclidMedium,
    color: COLORS.ErrorRed,
    // fontSize: SIZES.small,
    fontSize: SIZES.xSmall,
  },
  districtText: {
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.medium,
    color: COLORS.PrimaryText,
  },
  globalHead: {
    flex: 1,
    backgroundColor: COLORS.white,
    alignItems: "center",
    paddingVertical: pixelSizeVertical(15),
    paddingHorizontal: pixelSizeHorizontal(15),
  },
  cardBtnText: {
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.size13,
    color: COLORS.PrimaryText,
  },
  cardDateText: {
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.small,
    color: COLORS.SecondaryText,
  },
  cardHeadlineText: {
    fontFamily: FONT.EuclidMedium,
    color: COLORS.PrimaryText,
    fontSize: SIZES.size15,
  },
  cardTexts: {
    fontFamily: FONT.EuclidMedium,
    color: COLORS.SecondaryText,
    fontSize: SIZES.size13,
  },
  cardDot: {
    width: widthPixel(4),
    height: heightPixel(4),
    backgroundColor: COLORS.SecondaryText,
    borderRadius: 50,
  },
  overAllHeadLine: {
    fontFamily: FONT.EuclidSemiBold,
    color: COLORS.PrimaryText,
    fontSize: SIZES.medium,
  },
  overAllHeadLinePrimary: {
    fontFamily: FONT.EuclidSemiBold,
    color: COLORS.primary,
    fontSize: SIZES.medium,
  },
  spaceBetweenContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: ASPECTRADIO.width * 0.93,
  },

  // recent and all activity card
  cardContainer: {
    width: UNIQUEWIDTH.wid,
    backgroundColor: COLORS.Secondary,
    borderRadius: 8,
    height: heightPixel(150),
    marginVertical: pixelSizeVertical(20),
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // width: "50%",
  },
  ContainerTop: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BorderColor,
    padding: 15,
    height: heightPixel(60),
  },
  ContainerBottom: {
    flexDirection: "column",
    gap: 10,
    paddingHorizontal: pixelSizeHorizontal(15),
    height: heightPixel(90),
    justifyContent: "center",
  },
  flexJusSB: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems:'center'
  },

  dateText: {
    fontFamily: FONT.EuclidSemiBold,
    fontSize: SIZES.size14,
    color: COLORS.primary,
  },
  placeHolderText: {
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.size14,
    color: COLORS.PlaceHolderText,
  },

  floatBtn: {
    position: "absolute",
    bottom: heightPixel(110),
    right: 15,
    width: widthPixel(55),
    height: heightPixel(55),
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelBtn: {
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.medium,
    color: COLORS.primary,
  },
  searchBar: {
    width: "100%",
    height: heightPixel(53),
    borderWidth: 1,
    borderColor: COLORS.BorderColor,
    borderRadius: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: pixelSizeHorizontal(10),
  },
  inputText: {
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.size14,
    color: COLORS.primary,
  },

  btnFillText: {
    color: COLORS.white,
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.small,
  },
  btnUnfill: {
    width: widthPixel(171),
    height: heightPixel(48),
    backgroundColor: COLORS.white,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  txtLot: {
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.size14,
    color: COLORS.PrimaryText,
  },
  filteredHeadTxt: {
    fontFamily: FONT.EuclidSemiBold,
    fontSize: SIZES.small,
    color: COLORS.SecondaryText,
  },
  districtTxt: {
    // marginTop: pixelSizeVertical(5),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BorderColor,
    paddingVertical: pixelSizeVertical(20),
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.medium,
    color: COLORS.PrimaryText,
  },
  districtTextw: {
    marginTop: pixelSizeVertical(5),
    // borderBottomWidth: 1,
    // borderBottomColor: COLORS.BorderColor,
    paddingVertical: pixelSizeVertical(20),
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.medium,
    color: COLORS.PrimaryText,
  },
  DropdownHead: {
    position: "absolute",
    top: heightPixel(100),
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
    width: UNIQUEWIDTH.wid,
    // height:heightPixel(290),
    backgroundColor: COLORS.white,
    elevation: 3,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  listHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: pixelSizeHorizontal(15),
    paddingVertical: pixelSizeVertical(8),
  },
  DateInputHead: {
    width: widthPixel(183),
    height: heightPixel(54),
    borderWidth: 1,
    borderColor: COLORS.BorderColor,
    borderRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: pixelSizeHorizontal(10),
  },
  onBoaringHeadLine: {
    width: widthPixel(283),
    fontFamily: FONT.EuclidBold,
    fontSize: SIZES.xmedium,
    color: COLORS.primary,
    textAlign: "center",
  },
  onBoaringText: {
    width: widthPixel(326),
    fontFamily: FONT.EuclidRegular,
    fontSize: SIZES.medium,
    color: COLORS.SecondaryText,
    textAlign: "center",
  },
  zeroStateHelperTxt: {
    width: widthPixel(300),
    fontFamily: FONT.EuclidRegular,
    fontSize: SIZES.size14,
    color: COLORS.SecondaryText,
  },
  tabelText: {
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.small,
    color: COLORS.PrimaryText,
  },
  idText: {
    fontFamily: FONT.EuclidMedium,
    fontSize: SIZES.size14,
    color: COLORS.SecondaryText,
  },
  privacyPolciAndAboutText: {
    fontFamily: FONT.EuclidRegular,
    fontSize: SIZES.medium,
    color: COLORS.SecondaryText,
    width: widthPixel(353),
    textAlign: "left",
  },
  rowSpaceBetweenCenter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  reimText: {
    fontFamily: FONT.EuclidRegular,
    fontSize: SIZES.size14, 
    color: COLORS.PrimaryText,
  },
  dateTextReim: {
    fontFamily: FONT.EuclidSemiBold,
    fontSize: SIZES.size14,
    color: COLORS.primary,
  },
  btnNextContainer: {
    width: ASPECTRADIO.width,
    height: heightPixel(90),
    backgroundColor: COLORS.white,
    position: "absolute",
    top: "94%",
    justifyContent: "center",
    // alignItems: "center",
    shadowColor: "#101518",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: -3 },
    shadowRadius: 35,
  },
  btnNext: {
    height: heightPixel(48),
    width: UNIQUEWIDTH.wid,
    backgroundColor: COLORS.primary,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  head: {
    flex: 1,
    backgroundColor: COLORS.white,
    alignItems: "center",
    paddingVertical: pixelSizeVertical(15),
  },
});
